### import numpy library

In [1]:
import numpy as np

### 1. creating arrays - np.array()

#### 1-d array

In [2]:
a = np.array(
              [1,2,3]
            )
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


#### 2-d array

In [3]:
b = np.array(
  [
    (1,2),
    (3,4)
  ],
  dtype = float
)
print(b)

[[1. 2.]
 [3. 4.]]


#### 3-d array

In [4]:
c  = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8]
        ],
        [
            [1, 2, 3, 4],
            [9, 10, 11, 12]
        ]
    ],
    dtype=np.float64)

print(c)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 1.  2.  3.  4.]
  [ 9. 10. 11. 12.]]]


#### details of array

In [5]:
c

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 1.,  2.,  3.,  4.],
        [ 9., 10., 11., 12.]]])

In [6]:
c.data # prints memory address

In [7]:
c.shape

(2, 2, 4)

In [8]:
c.dtype

dtype('float64')

In [9]:
c.strides 
# number of bytes to skip in memory to move to the next position 
# along a certain axis

(64, 32, 8)

In [10]:
c.tolist()

[[[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0]],
 [[1.0, 2.0, 3.0, 4.0], [9.0, 10.0, 11.0, 12.0]]]

### initial placeholders

#### array of zeros - np.zeros()

In [11]:
d = np.zeros(
    shape = (3,4),
    dtype = np.int64
)
print(d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### array of ones - np.ones()

In [12]:
e = np.ones(
    shape = (2,3,4),
    dtype = np.int16
)
print(e)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


#### array of evenly spaced values (step value) - np.arange()

In [13]:
f = np.arange(start = 10, stop = 25, step = 5)
print(f)

[10 15 20]


#### array of evenly spaced values (number of samples) - np.linspace()

In [14]:
g = np.linspace(start = 0, stop = 2, num = 9, endpoint = True)
print(g)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


#### constant array - np.full()

In [15]:
h = np.full(
    shape = (2,3),
    fill_value = 5.7,
    dtype = float
)
print(h)

[[5.7 5.7 5.7]
 [5.7 5.7 5.7]]


#### identity matrix - np.eye()

In [16]:
i = np.eye(
    N= 10,
    M = 5,
    k = -2, # 0 Diagonal, +ve Upper Diagonal, -ve Lower Diagonal
    dtype = np.int64
)
print(i)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### random valued array - np.random.random()

In [17]:
j = np.random.random(  # [0.0, 1.0).
    size = (3,3)
)
print(j)

[[0.00974477 0.91264622 0.83481081]
 [0.13346756 0.73266758 0.37220138]
 [0.88316637 0.98936667 0.70362355]]


#### empty array - np.empty()

In [18]:
k = np.empty(
    shape = (3,3),
    dtype = np.int64
)
print(k) # garbage values

[[4576771101355545728 4606395605912780025 4605694526854615303]
 [4593976696047439624 4604774502434708158 4600376603912067686]
 [4606130075048292595 4607086642254886726 4604512897057072974]]


### 2. input_output

### saving and loading numpy arrays

#### np.save() 

In [19]:
# Create an array
my_array = np.array([1, 2, 3, 4, 5])

# Save the array to an .npy file
np.save("my_array.npy", my_array)

#### np.load()

In [20]:
# Load the array from the npy file
loaded_array = np.load("my_array.npy")

# Print the loaded array
print(loaded_array)

[1 2 3 4 5]


#### np.savez()

In [21]:
# Create some sample arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

# Save the arrays to an npz file
np.savez("my_arrays.npz", my_array1=array1, my_array2=array2, my_array3=array3)

In [22]:
# Load the arrays from the npz file
loaded_data = np.load("my_arrays.npz")

# Access the arrays using the specified names
loaded_array1 = loaded_data["my_array1"]
loaded_array2 = loaded_data["my_array2"]
loaded_array3 = loaded_data["my_array3"]

# Print the loaded arrays
print(loaded_array1)
print(loaded_array2)
print(loaded_array3)

[1 2 3]
[4 5 6]
[7 8 9]


### saving and loading text files

#### np.savetxt()

In [23]:
a = np.arange(0.0, 5.0, 1.0)
a

array([0., 1., 2., 3., 4.])

In [24]:
np.savetxt('my_array.txt', a, delimiter=',')

In [25]:
np.savetxt('my_array.csv', a, delimiter=',') # comma seperated values

In [26]:
np.savetxt('my_array.out', a, delimiter=',') # assembler output

#### np.genfromtxt()

In [27]:
# Load data from a text file
arr = np.genfromtxt('data.txt', skip_header=1)
arr

array([[0.2536, 0.1008, 0.3857],
       [0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.5929],
       [0.1781, 0.3049, 0.8928],
       [0.6253, 0.3486, 0.8791]])

In [28]:
arr = np.genfromtxt('data2.txt')
arr

array([[   nan,    nan,    nan],
       [0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875,    nan],
       [0.1781, 0.3049, 0.8928],
       [   nan, 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])

In [29]:
arr = np.genfromtxt('data2.txt',
                    skip_header=1,
                    filling_values=-99)
arr

array([[  0.4839,   0.4536,   0.3561],
       [  0.1292,   0.6875, -99.    ],
       [  0.1781,   0.3049,   0.8928],
       [-99.    ,   0.5801,   0.2038],
       [  0.5993,   0.4357,   0.741 ]])

#### np.loadtxt()

In [30]:
 arr = np.loadtxt('data2.txt', 
                  dtype = str, 
                  delimiter = '\n')
 print(arr)
 print(type(arr))

['Value1  Value2  Value3' '0.4839  0.4536  0.3561'
 '0.1292  0.6875  MISSING' '0.1781  0.3049  0.8928'
 'MISSING 0.5801  0.2038' '0.5993  0.4357  0.7410']
<class 'numpy.ndarray'>


In [31]:
x, y, z = np.loadtxt('data.txt',
                    skiprows=1,
                    unpack=True)
print(x)
print(y)
print(z)
print(type(z))

[0.2536 0.4839 0.1292 0.1781 0.6253]
[0.1008 0.4536 0.6875 0.3049 0.3486]
[0.3857 0.3561 0.5929 0.8928 0.8791]
<class 'numpy.ndarray'>


In [32]:
# x, y, z = np.loadtxt('data2.txt', skiprows=1, unpack=True)
# ValueError: could not convert string to float: 'MISSING'

### 3. inspecting array

In [33]:
a = np.array(
    [
      [1,2,3,4],
      [5,6,7,8],
      [9,10,11,12]
    ],
    dtype=np.int64)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int64)

#### length

In [34]:
len(a) # rows

3

#### dimensions

In [35]:
a.shape # (rows,columns)

(3, 4)

#### number of dimensions

In [36]:
a.ndim

2

#### number of elements

In [37]:
a.size # rows*columns 

12

#### memory details

In [38]:
a.itemsize # Length of one array element in bytes

8

In [39]:
a.nbytes # Total consumed bytes by the array elements np.size*np.itemsize

96

#### datatype of elements

In [40]:
a.dtype

dtype('int64')

name of datatype

In [41]:
a.dtype.name

'int64'

#### convert array to a different type

In [42]:
print(type(a[0][0]))

b = a.astype(np.str_)

print(type(b[0][0]))

<class 'numpy.int64'>
<class 'numpy.str_'>


### String array

In [43]:
s = np.array([['a','an','the'],['python','is','easy']])
s

array([['a', 'an', 'the'],
       ['python', 'is', 'easy']], dtype='<U6')

In [44]:
len(s)

2

In [45]:
s.shape

(2, 3)

In [46]:
s.ndim

2

In [47]:
s.size # considers largest string size

6

In [48]:
s.itemsize

24

In [49]:
s.nbytes

144

In [50]:
s.dtype

dtype('<U6')

In [51]:
s.dtype.name

'str192'

In [52]:
print(s[0][0].dtype)

b = s.astype(np.string_)

print(b[0][0].dtype)

<U1
|S1


### 4. datatypes

***numpy data types***

- np.int64 # Signed 64-bit integer types
- np.float32 # 8 bits exponent, 23 bits mantissa
- np.double # 11 bits exponent, 52 bits mantissa
- complex # Complex numbers represented by 128 floats
- bool # Boolean type storing TRUE and FALSE values
- object # Python object type
- np.string_ # Fixed-length string type
- np.unicode_ # Fixed-length unicode 

***referring datatypes with 1 character:***

- i # integer
- b # boolean
- u # unsigned integer
- f # float
- c # complex float
- m # timedelta
- M # datetime
- O # object
- S # string
- U # unicode string
- V # fixed chunk of memory for other type ( void )

In [53]:
arr = np.array([1, 2, 3, 4], dtype='U')
print(arr)
print(arr.data)

['1' '2' '3' '4']


In [54]:
# arr = np.array(['a', '2', '3'], dtype='i') #ValueError: invalid literal for int() with base 10: 'a'

In [55]:
a = np.power(100, 8, dtype=np.int64) # correct
b = np.power(100, 8, dtype=np.int32) # incorrect 
c = np.array([1, 2, 3], dtype='f') # f => float32

print(a,b,c,type(c[0]))

10000000000000000 1874919424 [1. 2. 3.] <class 'numpy.float32'>


#### casting

In [56]:
arr2 = arr.astype(float)
arr, arr2

(array(['1', '2', '3', '4'], dtype='<U1'), array([1., 2., 3., 4.]))

### 5. math operations

***shape should match***

In [57]:
# Initialize a 3x4 array of ones and assign it to the variable `x`
x = np.full((3,4),7)

# Print the shape of the array `x`
print(x)
print("Shape of x:", x.shape)

# Initialize a 3x4 array of random numbers between 0 and 1 and assign it to the variable `y`
y = np.full((3,4),2)

# Print the shape of the array `y`
print(y)
print("Shape of y:", y.shape)

# Add the arrays `x` and `y` element-wise and print the resulting array
z = x + y
print("Result of x + y:\n", z)

# Print the shape of the resulting array
print("Shape of x + y:", z.shape)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Shape of x: (3, 4)
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
Shape of y: (3, 4)
Result of x + y:
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
Shape of x + y: (3, 4)


***one of the array has only one element***

In [58]:
# Initialize a array with 1 element and assign it to the variable `x`
x = np.array([3])

# Print the shape of the array `x`
print(x)
print("Shape of x:", x.ndim)

# Initialize a 3x4 array of random numbers between 0 and 1 and assign it to the variable `y`
y = np.full((3,4),5)

# Print the shape of the array `y`
print(y)
print("Shape of y:", y.shape)

# Add the arrays `x` and `y` element-wise and print the resulting array
z = x + y
print("Result of x + y:\n", z)

# Print the shape of the resulting array
print("Shape of x + y:", z.shape)

[3]
Shape of x: 1
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape of y: (3, 4)
Result of x + y:
 [[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
Shape of x + y: (3, 4)


***compatible in all dimensions***

In [59]:
# Initialize 'x' and 'y' (columns are equal)
x = np.ones((2,3))
y = np.full((5,1,3),4)

print('x:',x)
print('y:',y)

# Add 'x' and 'y'
z = x + y
print('z:',z)

x: [[1. 1. 1.]
 [1. 1. 1.]]
y: [[[4 4 4]]

 [[4 4 4]]

 [[4 4 4]]

 [[4 4 4]]

 [[4 4 4]]]
z: [[[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]]


***value error - if shape is not compatible***

In [60]:
# Initialize 'x' and 'y' (columns are not equal)
x = np.ones((1,2))
y = np.random.random((1,3))

# print(x+y)
# ValueError: operands could not be broadcast together with shapes (1,2) (1,3) 

#### arithmetic operations

In [61]:
a = np.array([[0,1,2,3],[10,20,30,40]])
b = np.array([[9,2,6,0],[2,4,6,8]])
a,b

(array([[ 0,  1,  2,  3],
        [10, 20, 30, 40]]),
 array([[9, 2, 6, 0],
        [2, 4, 6, 8]]))

In [62]:
addition1 = a + b
addition2 = np.add(a,b)

print(addition1)
print(addition2)

[[ 9  3  8  3]
 [12 24 36 48]]
[[ 9  3  8  3]
 [12 24 36 48]]


In [63]:
sub1 = a - b
sub2 = np.subtract(a,b)

print(sub1)
print(sub2)

[[-9 -1 -4  3]
 [ 8 16 24 32]]
[[-9 -1 -4  3]
 [ 8 16 24 32]]


In [64]:
mul1 = a*b
mul2 = np.multiply(a,b)

print(mul1)
print(mul2)

[[  0   2  12   0]
 [ 20  80 180 320]]
[[  0   2  12   0]
 [ 20  80 180 320]]


In [65]:
div1 = b/a
div2 = np.divide(b,a)

print(div1)
print(div2)

[[inf 2.  3.  0. ]
 [0.2 0.2 0.2 0.2]]
[[inf 2.  3.  0. ]
 [0.2 0.2 0.2 0.2]]


C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_31864\2470102.py:1: RuntimeWarning: divide by zero encountered in true_divide
  div1 = b/a
C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_31864\2470102.py:2: RuntimeWarning: divide by zero encountered in true_divide
  div2 = np.divide(b,a)


In [66]:
np.exp(a) # e power ...

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17]])

In [67]:
np.sqrt(b)

array([[3.        , 1.41421356, 2.44948974, 0.        ],
       [1.41421356, 2.        , 2.44948974, 2.82842712]])

In [68]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.54402111,  0.91294525, -0.98803162,  0.74511316]])

In [69]:
np.cos(a)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.83907153,  0.40808206,  0.15425145, -0.66693806]])

In [70]:
print(np.log(a)) # element wise natural logarithm

[[      -inf 0.         0.69314718 1.09861229]
 [2.30258509 2.99573227 3.40119738 3.68887945]]


C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_31864\2740407513.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(a)) # element wise natural logarithm


In [71]:
a = np.full(shape=2,fill_value=5)
b = np.full(2,6)
print(a)
print(b)
a.dot(b) # d0t product

[5 5]
[6 6]


60

In [72]:
a = np.full(shape=(2,2),fill_value=5)
b = np.full((2,2),6)
print(a)
print(b)
a.dot(b) # d0t product

[[5 5]
 [5 5]]
[[6 6]
 [6 6]]


array([[60, 60],
       [60, 60]])

### comparision operations

In [73]:
a = np.array([1,2,3])
b = np.array([1,2,4])
print(a)
print(b)

print(a == b) # element wise comparision
print(a < 2) # element wise comparision
print(np.array_equal(a,b)) # array wise comparison

c = b
print(np.array_equal(b,c))

[1 2 3]
[1 2 4]
[ True  True False]
[ True False False]
False
True


#### aggregate functions

In [74]:
a = np.array([[10,20,30],[21,43,23],[3,8,4]])
print(a)
# a, type(a)cal

[[10 20 30]
 [21 43 23]
 [ 3  8  4]]


In [75]:
a.sum() # array wise sum

162

In [76]:
a.min() # array wise min value

3

In [77]:
a.max() # array wise max value

43

In [78]:
a.cumsum() # cumulative sum of elements

array([ 10,  30,  60,  81, 124, 147, 150, 158, 162])

In [79]:
a.mean() # mean of elements in array
# sum = 10+20+30+21+43+23 = 147
# mean = 147/6 = 24.5

18.0

In [80]:
np.median(a) # median of elements in array
# sorted => 10,20,21,23,30,43
# median => (21+23)/2 = 22

20.0

In [81]:
print(np.corrcoef(a)) # correlation coefficient (row wise)
# https://www.statskingdom.com/correlation-calculator.html

[[1.         0.08219949 0.18898224]
 [0.08219949 1.         0.99419163]
 [0.18898224 0.99419163 1.        ]]


In [82]:
b = np.array([[10,16,30],[3,9,6]])
c = np.array([[13,67,15],[12,98,56]])
# print(b)
# print(c)
print(np.corrcoef(b,c)) 
# correlation coefficient = cov(x,y)/sqrt(var(x) * var(y))
# cov(x,y) = (Sum(Xi - Xmean)(Yi - Ymean) / N-1)

[[ 1.          0.29230641 -0.1930724   0.30511924]
 [ 0.29230641  1.          0.8818947   0.99990987]
 [-0.1930724   0.8818947   1.          0.8754858 ]
 [ 0.30511924  0.99990987  0.8754858   1.        ]]


In [83]:
b.mean(),c.mean()

(12.333333333333334, 43.5)

In [174]:
a = np.array([[1,200],[5,400],[10,500]])
print(a)


[[  1 200]
 [  5 400]
 [ 10 500]]


In [175]:
np.std(a, axis = 0) # standard deviation = sqrt(mean(x)) 
# https://www.calculator.net/standard-deviation-calculator.html 

array([  3.68178701, 124.72191289])

**axis = 0 => row wise**

**axis = 1 => column wise**

In [177]:
print(np.var(a,axis=0), np.std(a,axis=0))
print(np.var(a,axis=1), np.std(a,axis=1))
print(np.var(a), np.std(a))

[1.35555556e+01 1.55555556e+04] [  3.68178701 124.72191289]
[ 9900.25 39006.25 60025.  ] [ 99.5 197.5 245. ]
40425.0 201.05969262883102


### 6. copying arrays

***shape should match***

In [85]:
# Initialize a 3x4 array of ones and assign it to the variable `x`
x = np.full((3,4),7)

# Print the shape of the array `x`
print(x)
print("Shape of x:", x.shape)

# Initialize a 3x4 array of random numbers between 0 and 1 and assign it to the variable `y`
y = np.full((3,4),2)

# Print the shape of the array `y`
print(y)
print("Shape of y:", y.shape)

# Add the arrays `x` and `y` element-wise and print the resulting array
z = x + y
print("Result of x + y:\n", z)

# Print the shape of the resulting array
print("Shape of x + y:", z.shape)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Shape of x: (3, 4)
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
Shape of y: (3, 4)
Result of x + y:
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
Shape of x + y: (3, 4)


***one of the array has only one element***

In [86]:
# Initialize a array with 1 element and assign it to the variable `x`
x = np.array([3])

# Print the shape of the array `x`
print(x)
print("Shape of x:", x.ndim)

# Initialize a 3x4 array of random numbers between 0 and 1 and assign it to the variable `y`
y = np.full((3,4),5)

# Print the shape of the array `y`
print(y)
print("Shape of y:", y.shape)

# Add the arrays `x` and `y` element-wise and print the resulting array
z = x + y
print("Result of x + y:\n", z)

# Print the shape of the resulting array
print("Shape of x + y:", z.shape)

[3]
Shape of x: 1
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape of y: (3, 4)
Result of x + y:
 [[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
Shape of x + y: (3, 4)


***compatible in all dimensions***

In [87]:
# Initialize 'x' and 'y' (columns are equal)
x = np.ones((2,3))
y = np.full((5,1,3),4)

print('x:',x)
print('y:',y)

# Add 'x' and 'y'
z = x + y
print('z:',z)

x: [[1. 1. 1.]
 [1. 1. 1.]]
y: [[[4 4 4]]

 [[4 4 4]]

 [[4 4 4]]

 [[4 4 4]]

 [[4 4 4]]]
z: [[[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]]


***value error - if shape is not compatible***

In [88]:
# Initialize 'x' and 'y' (columns are not equal)
x = np.ones((1,2))
y = np.random.random((1,3))

# print(x+y)
# ValueError: operands could not be broadcast together with shapes (1,2) (1,3) 

#### arithmetic operations

In [89]:
a = np.array([[0,1,2,3],[10,20,30,40]])
b = np.array([[9,2,6,0],[2,4,6,8]])
a,b

(array([[ 0,  1,  2,  3],
        [10, 20, 30, 40]]),
 array([[9, 2, 6, 0],
        [2, 4, 6, 8]]))

In [90]:
addition1 = a + b
addition2 = np.add(a,b)

print(addition1)
print(addition2)

[[ 9  3  8  3]
 [12 24 36 48]]
[[ 9  3  8  3]
 [12 24 36 48]]


In [91]:
sub1 = a - b
sub2 = np.subtract(a,b)

print(sub1)
print(sub2)

[[-9 -1 -4  3]
 [ 8 16 24 32]]
[[-9 -1 -4  3]
 [ 8 16 24 32]]


In [92]:
mul1 = a*b
mul2 = np.multiply(a,b)

print(mul1)
print(mul2)

[[  0   2  12   0]
 [ 20  80 180 320]]
[[  0   2  12   0]
 [ 20  80 180 320]]


In [93]:
div1 = b/a
div2 = np.divide(b,a)

print(div1)
print(div2)

[[inf 2.  3.  0. ]
 [0.2 0.2 0.2 0.2]]
[[inf 2.  3.  0. ]
 [0.2 0.2 0.2 0.2]]


C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_31864\2470102.py:1: RuntimeWarning: divide by zero encountered in true_divide
  div1 = b/a
C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_31864\2470102.py:2: RuntimeWarning: divide by zero encountered in true_divide
  div2 = np.divide(b,a)


In [94]:
np.exp(a) # e power ...

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17]])

In [95]:
np.sqrt(b)

array([[3.        , 1.41421356, 2.44948974, 0.        ],
       [1.41421356, 2.        , 2.44948974, 2.82842712]])

In [96]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.54402111,  0.91294525, -0.98803162,  0.74511316]])

In [97]:
np.cos(a)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.83907153,  0.40808206,  0.15425145, -0.66693806]])

In [98]:
print(np.log(a)) # element wise natural logarithm

[[      -inf 0.         0.69314718 1.09861229]
 [2.30258509 2.99573227 3.40119738 3.68887945]]


C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_31864\2740407513.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(a)) # element wise natural logarithm


In [99]:
a = np.full(shape=2,fill_value=5)
b = np.full(2,6)
print(a)
print(b)
a.dot(b) # d0t product

[5 5]
[6 6]


60

In [100]:
a = np.full(shape=(2,2),fill_value=5)
b = np.full((2,2),6)
print(a)
print(b)
a.dot(b) # d0t product

[[5 5]
 [5 5]]
[[6 6]
 [6 6]]


array([[60, 60],
       [60, 60]])

### comparision operations

In [101]:
a = np.array([1,2,3])
b = np.array([1,2,4])
print(a)
print(b)

print(a == b) # element wise comparision
print(a < 2) # element wise comparision
print(np.array_equal(a,b)) # array wise comparison

c = b
print(np.array_equal(b,c))

[1 2 3]
[1 2 4]
[ True  True False]
[ True False False]
False
True


#### aggregate functions

In [102]:
a = np.array([[10,20,30],[21,43,23],[3,8,4]])
print(a)
# a, type(a)cal

[[10 20 30]
 [21 43 23]
 [ 3  8  4]]


In [103]:
a.sum() # array wise sum

162

In [104]:
a.min() # array wise min value

3

In [105]:
a.max() # array wise max value

43

In [106]:
a.cumsum() # cumulative sum of elements

array([ 10,  30,  60,  81, 124, 147, 150, 158, 162])

In [107]:
a.mean() # mean of elements in array
# sum = 10+20+30+21+43+23 = 147
# mean = 147/6 = 24.5

18.0

In [108]:
np.median(a) # median of elements in array
# sorted => 10,20,21,23,30,43
# median => (21+23)/2 = 22

20.0

In [109]:
print(np.corrcoef(a)) # correlation coefficient (row wise)
# https://www.statskingdom.com/correlation-calculator.html

[[1.         0.08219949 0.18898224]
 [0.08219949 1.         0.99419163]
 [0.18898224 0.99419163 1.        ]]


In [110]:
b = np.array([[10,16,30],[3,9,6]])
c = np.array([[13,67,15],[12,98,56]])
# print(b)
# print(c)
print(np.corrcoef(b,c)) 
# correlation coefficient = cov(x,y)/sqrt(var(x) * var(y))
# cov(x,y) = (Sum(Xi - Xmean)(Yi - Ymean) / N-1)

[[ 1.          0.29230641 -0.1930724   0.30511924]
 [ 0.29230641  1.          0.8818947   0.99990987]
 [-0.1930724   0.8818947   1.          0.8754858 ]
 [ 0.30511924  0.99990987  0.8754858   1.        ]]


In [111]:
b.mean(),c.mean()

(12.333333333333334, 43.5)

In [112]:
a = np.array([[1,2],[10,20],[4,5]])
a, np.std(a, axis = 0) # standard deviation = sqrt(mean(x)) 
# https://www.calculator.net/standard-deviation-calculator.html 
# 1,10,4
# 2,20,5

(array([[ 1,  2],
        [10, 20],
        [ 4,  5]]),
 array([3.74165739, 7.87400787]))

**axis = 0 => row wise**

**axis = 1 => column wise**

### 7. sorting arrays

In [113]:
a = np.array([[4,2,5,2,6,4,8,3,7,5],[6,2,8,3,5,2,8,9,4,6]])
print(a) 

[[4 2 5 2 6 4 8 3 7 5]
 [6 2 8 3 5 2 8 9 4 6]]


In [114]:
a.sort() # row wise sort
print(a)

[[2 2 3 4 4 5 5 6 7 8]
 [2 2 3 4 5 6 6 8 8 9]]


In [115]:
a = np.array([[4,2,5,2,6,4,8,3,7,5],[6,2,8,3,5,2,8,9,4,6]])
print(a)

[[4 2 5 2 6 4 8 3 7 5]
 [6 2 8 3 5 2 8 9 4 6]]


In [116]:
a.sort(axis = 0) # column wise sort
print(a)

[[4 2 5 2 5 2 8 3 4 5]
 [6 2 8 3 6 4 8 9 7 6]]


### 8. Indexing, subsetting, slicing

In [117]:
a = np.array([[4,2,5,2,6,4,8,3,7,5],[6,2,8,3,5,2,8,9,4,10]])
print(a) 

[[ 4  2  5  2  6  4  8  3  7  5]
 [ 6  2  8  3  5  2  8  9  4 10]]


#### indexing

In [118]:
a[0]

array([4, 2, 5, 2, 6, 4, 8, 3, 7, 5])

In [119]:
a[0][2]

5

In [120]:
a[-1]

array([ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10])

In [121]:
a[-1][2]

8

In [122]:
a[-1][-3]

9

#### boolean indexing

In [123]:
# a>5
a[a>5]

array([ 6,  8,  7,  6,  8,  8,  9, 10])

#### fancy indexing

In [124]:
a

array([[ 4,  2,  5,  2,  6,  4,  8,  3,  7,  5],
       [ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10]])

In [125]:
print(a[0][0], a[0][1], a[-1][-1], a[1][4])
print(a[[0,0,-1,1],[0,1,-1,4]]) # (0,0) (0,1) (-1,-1) (1,4)

4 2 10 5
[ 4  2 10  5]


In [126]:
a[[1,0,1,0]][:,[0,1,8,9]]

array([[ 6,  2,  4, 10],
       [ 4,  2,  7,  5],
       [ 6,  2,  4, 10],
       [ 4,  2,  7,  5]])

#### subsetting

In [127]:
a

array([[ 4,  2,  5,  2,  6,  4,  8,  3,  7,  5],
       [ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10]])

In [128]:
print(a[0][9], # indexing
      a[0,9]) # subsetting
print(a[1,:])

5 5
[ 6  2  8  3  5  2  8  9  4 10]


#### slicing

In [129]:
a

array([[ 4,  2,  5,  2,  6,  4,  8,  3,  7,  5],
       [ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10]])

In [130]:
a[:]

array([[ 4,  2,  5,  2,  6,  4,  8,  3,  7,  5],
       [ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10]])

In [131]:
a[0:1]

array([[4, 2, 5, 2, 6, 4, 8, 3, 7, 5]])

In [132]:
a[0:2,1]

array([2, 2])

In [133]:
a[:-1,0][0]

4

In [134]:
a[1, ...] # a[1,:]

array([ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10])

In [135]:
a_1d = np.arange(1,25,2)
print(a_1d)
print(a_1d.ndim)

[ 1  3  5  7  9 11 13 15 17 19 21 23]
1


In [136]:
a_1d[-1:-4:-1] # subset

array([23, 21, 19])

In [137]:
a_2d = a_1d.reshape((3,4)) # 3*4 = 12
print(a_2d)
print(a_2d.ndim)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
2


In [138]:
a_2d[1:,:2]  # submatrix

array([[ 9, 11],
       [17, 19]])

In [139]:
a_3d = a_1d.reshape((1,3,4)) # 3*4 = 12
print(a_3d)
print(a_3d.ndim)

[[[ 1  3  5  7]
  [ 9 11 13 15]
  [17 19 21 23]]]
3


In [140]:
a_3d[0,:,:]

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [141]:
a_3d[0, ...]

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

**slicing is shallow copy**

In [142]:
a = np.array([[4,2,5,2,6,4,8,3,7,5],[6,2,8,3,5,2,8,9,4,10]])
b = a[:]
print(id(a)==id(b), id(a[0])==id(b[0]))
print(a)
print(b)

False True
[[ 4  2  5  2  6  4  8  3  7  5]
 [ 6  2  8  3  5  2  8  9  4 10]]
[[ 4  2  5  2  6  4  8  3  7  5]
 [ 6  2  8  3  5  2  8  9  4 10]]


In [143]:
b[0] = [ 40,  20,  50,  20,  60,  40,  80,  30,  70,  50]
print(a)
print(b)

[[40 20 50 20 60 40 80 30 70 50]
 [ 6  2  8  3  5  2  8  9  4 10]]
[[40 20 50 20 60 40 80 30 70 50]
 [ 6  2  8  3  5  2  8  9  4 10]]


In [144]:
b = [1,2,3]
print(a)
print(b)

[[40 20 50 20 60 40 80 30 70 50]
 [ 6  2  8  3  5  2  8  9  4 10]]
[1, 2, 3]


### 9. array manipulation

In [145]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.shape

(9,)

#### change shape of array

In [146]:
# returns array with given dimensions, no change in data
b = a.reshape(3,3)
print(b, b.shape, a, a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) [1 2 3 4 5 6 7 8 9] (9,)


In [147]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
a.resize((3,3)) # original array shape is changed
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### flatten array

In [148]:
c = b.ravel() # returns flatten array (no effect to original array)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### transposing array

In [149]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [150]:
# no effect on original array, returns new array 
# shallow copy
b1 = np.transpose(b) 
b2 = b.T
b1,b2,b

(array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

#### add elements to array

In [151]:
np.append(a,[-9,-3]), a, a.shape
# original array is not changed

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, -9, -3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [152]:
np.insert(a,1,-99), a
# original array is not changed

(array([  1, -99,   2,   3,   4,   5,   6,   7,   8,   9]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

#### remove elements from array

In [153]:
a, np.delete(a,1), a
# original array is not changed

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([1, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

#### combining arrays

##### np.concatenate()

In [154]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0)) # row wise concatenation

[[1 2]
 [3 4]
 [5 6]]


In [155]:
print(np.concatenate((a, b.T), axis=1)) # column wise concatenation

[[1 2 5]
 [3 4 6]]


In [156]:
print(np.concatenate((a, b), axis=None)) # flattened

[1 2 3 4 5 6]


##### np.hstack()

In [157]:
# Stack arrays horizontally (column wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [158]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

##### np.vstack()

In [159]:
# Stack arrays in sequence vertically (row wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

##### np.r_()

In [161]:
# Stack arrays in sequence vertically (row wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [162]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.r_[a,b]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

##### np.column_stack()

In [163]:
# Stack 1-D arrays as columns into a 2-D array.
a = np.array((1,2,3))
b = np.array((4,5,6))
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

##### np.c_()

In [164]:
# Stack arrays in sequence vertically (row wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

#### splitting arrays

In [165]:
# Split an array into multiple sub-arrays horizontally (column-wise).
a = np.array([ [ 0.,   1.,   2.,   3.],
               [ 4.,   5.,   6.,   7.],
               [ 8.,   9.,  10.,  11.],
               [12.,  13.,  14.,  15.] ])
print(np.hsplit(a,2))

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


In [166]:
# Split an array into multiple sub-arrays vertically (row-wise).
np.vsplit(a,2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

### 10. numpy functions for data analysis