### import numpy library

In [2]:
import numpy as np

### creating arrays - np.array()

#### 1-d array

In [3]:
a = np.array(
              [1,2,3]
            )
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


#### 2-d array

In [4]:
b = np.array(
  [
    (1,2),
    (3,4)
  ],
  dtype = float
)
print(b)

[[1. 2.]
 [3. 4.]]


#### 3-d array

In [27]:
c  = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8]
        ],
        [
            [1, 2, 3, 4],
            [9, 10, 11, 12]
        ]
    ],
    dtype=np.float64)

print(c)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 1.  2.  3.  4.]
  [ 9. 10. 11. 12.]]]


#### details of array

In [35]:
c

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 1.,  2.,  3.,  4.],
        [ 9., 10., 11., 12.]]])

In [29]:
c.data # prints memory address

In [30]:
c.shape

(2, 2, 4)

In [31]:
c.dtype

dtype('float64')

In [32]:
c.strides 
# number of bytes to skip in memory to move to the next position 
# along a certain axis

(64, 32, 8)

In [36]:
c.tolist()

[[[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0]],
 [[1.0, 2.0, 3.0, 4.0], [9.0, 10.0, 11.0, 12.0]]]

### initial placeholders

#### array of zeros - np.zeros()

In [30]:
d = np.zeros(
    shape = (3,4),
    dtype = np.int64
)
print(d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### array of ones - np.ones()

In [15]:
e = np.ones(
    shape = (2,3,4),
    dtype = np.int16
)
print(e)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


#### array of evenly spaced values (step value) - np.arange()

In [24]:
f = np.arange(start = 10, stop = 25, step = 5)
print(f)

[10 15 20]


#### array of evenly spaced values (number of samples) - np.linspace()

In [22]:
g = np.linspace(start = 0, stop = 2, num = 9, endpoint = True)
print(g)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


#### constant array - np.full()

In [32]:
h = np.full(
    shape = (2,3),
    fill_value = 5.7,
    dtype = float
)
print(h)

[[5.7 5.7 5.7]
 [5.7 5.7 5.7]]


#### identity matrix - np.eye()

In [45]:
i = np.eye(
    N= 10,
    M = 5,
    k = -2, # 0 Diagonal, +ve Upper Diagonal, -ve Lower Diagonal
    dtype = np.int64
)
print(i)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### random valued array - np.random.random()

In [50]:
j = np.random.random(  # [0.0, 1.0).
    size = (3,3)
)
print(j)

[[0.91910884 0.9871958  0.93959576]
 [0.11154806 0.59041664 0.12048372]
 [0.0416645  0.99455491 0.96106233]]


#### empty array - np.empty()

In [24]:
k = np.empty(
    shape = (3,3),
    dtype = np.int64
)
print(k) # garbage values

[[                0                 0                 0]
 [                0                 0              1868]
 [32651513910263808                 0                 0]]
