In [7]:
import numpy as np

### saving and loading numpy arrays

#### np.save() 

In [8]:
# Create an array
my_array = np.array([1, 2, 3, 4, 5])

# Save the array to an .npy file
np.save("my_array.npy", my_array)

#### np.load()

In [9]:
# Load the array from the npy file
loaded_array = np.load("my_array.npy")

# Print the loaded array
print(loaded_array)

[1 2 3 4 5]


#### np.savez()

In [10]:
# Create some sample arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

# Save the arrays to an npz file
np.savez("my_arrays.npz", my_array1=array1, my_array2=array2, my_array3=array3)

In [11]:
# Load the arrays from the npz file
loaded_data = np.load("my_arrays.npz")

# Access the arrays using the specified names
loaded_array1 = loaded_data["my_array1"]
loaded_array2 = loaded_data["my_array2"]
loaded_array3 = loaded_data["my_array3"]

# Print the loaded arrays
print(loaded_array1)
print(loaded_array2)
print(loaded_array3)

[1 2 3]
[4 5 6]
[7 8 9]


### saving and loading text files

#### np.savetxt()

In [12]:
a = np.arange(0.0, 5.0, 1.0)
a

array([0., 1., 2., 3., 4.])

In [13]:
np.savetxt('my_array.txt', a, delimiter=',')

In [14]:
np.savetxt('my_array.csv', a, delimiter=',') # comma seperated values

In [16]:
np.savetxt('my_array.out', a, delimiter=',') # assembler output

#### np.genfromtxt()

In [30]:
# Load data from a text file
arr = np.genfromtxt('data.txt', skip_header=1)
arr

array([[0.2536, 0.1008, 0.3857],
       [0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.5929],
       [0.1781, 0.3049, 0.8928],
       [0.6253, 0.3486, 0.8791]])

In [28]:
arr = np.genfromtxt('data2.txt')
arr

array([[   nan,    nan,    nan],
       [0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875,    nan],
       [0.1781, 0.3049, 0.8928],
       [   nan, 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])

In [38]:
arr = np.genfromtxt('data2.txt',
                    skip_header=1,
                    filling_values=-99)
arr

array([[  0.4839,   0.4536,   0.3561],
       [  0.1292,   0.6875, -99.    ],
       [  0.1781,   0.3049,   0.8928],
       [-99.    ,   0.5801,   0.2038],
       [  0.5993,   0.4357,   0.741 ]])

#### np.loadtxt()

In [48]:
 arr = np.loadtxt('data2.txt', 
                  dtype = str, 
                  delimiter = '\n')
 print(arr)
 print(type(arr))

['Value1  Value2  Value3' '0.4839  0.4536  0.3561'
 '0.1292  0.6875  MISSING' '0.1781  0.3049  0.8928'
 'MISSING 0.5801  0.2038' '0.5993  0.4357  0.7410']
<class 'numpy.ndarray'>


In [50]:
x, y, z = np.loadtxt('data.txt',
                    skiprows=1,
                    unpack=True)
print(x)
print(y)
print(z)
print(type(z))

[0.2536 0.4839 0.1292 0.1781 0.6253]
[0.1008 0.4536 0.6875 0.3049 0.3486]
[0.3857 0.3561 0.5929 0.8928 0.8791]
<class 'numpy.ndarray'>


In [52]:
# x, y, z = np.loadtxt('data2.txt', skiprows=1, unpack=True)
# ValueError: could not convert string to float: 'MISSING'