In [172]:
import numpy as np

***shape should match***

In [173]:
# Initialize a 3x4 array of ones and assign it to the variable `x`
x = np.full((3,4),7)

# Print the shape of the array `x`
print(x)
print("Shape of x:", x.shape)

# Initialize a 3x4 array of random numbers between 0 and 1 and assign it to the variable `y`
y = np.full((3,4),2)

# Print the shape of the array `y`
print(y)
print("Shape of y:", y.shape)

# Add the arrays `x` and `y` element-wise and print the resulting array
z = x + y
print("Result of x + y:\n", z)

# Print the shape of the resulting array
print("Shape of x + y:", z.shape)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Shape of x: (3, 4)
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
Shape of y: (3, 4)
Result of x + y:
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
Shape of x + y: (3, 4)


***one of the array has only one element***

In [174]:
# Initialize a array with 1 element and assign it to the variable `x`
x = np.array([3])

# Print the shape of the array `x`
print(x)
print("Shape of x:", x.ndim)

# Initialize a 3x4 array of random numbers between 0 and 1 and assign it to the variable `y`
y = np.full((3,4),5)

# Print the shape of the array `y`
print(y)
print("Shape of y:", y.shape)

# Add the arrays `x` and `y` element-wise and print the resulting array
z = x + y
print("Result of x + y:\n", z)

# Print the shape of the resulting array
print("Shape of x + y:", z.shape)

[3]
Shape of x: 1
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape of y: (3, 4)
Result of x + y:
 [[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
Shape of x + y: (3, 4)


***compatible in all dimensions***

In [175]:
# Initialize 'x' and 'y' (columns are equal)
x = np.ones((2,3))
y = np.full((5,1,3),4)

print('x:',x)
print('y:',y)

# Add 'x' and 'y'
z = x + y
print('z:',z)

x: [[1. 1. 1.]
 [1. 1. 1.]]
y: [[[4 4 4]]

 [[4 4 4]]

 [[4 4 4]]

 [[4 4 4]]

 [[4 4 4]]]
z: [[[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]]]


***value error - if shape is not compatible***

In [176]:
# Initialize 'x' and 'y' (columns are not equal)
x = np.ones((1,2))
y = np.random.random((1,3))

# print(x+y)
# ValueError: operands could not be broadcast together with shapes (1,2) (1,3) 

#### arithmetic operations

In [177]:
a = np.array([[0,1,2,3],[10,20,30,40]])
b = np.array([[9,2,6,0],[2,4,6,8]])
a,b

(array([[ 0,  1,  2,  3],
        [10, 20, 30, 40]]),
 array([[9, 2, 6, 0],
        [2, 4, 6, 8]]))

In [178]:
addition1 = a + b
addition2 = np.add(a,b)

print(addition1)
print(addition2)

[[ 9  3  8  3]
 [12 24 36 48]]
[[ 9  3  8  3]
 [12 24 36 48]]


In [179]:
sub1 = a - b
sub2 = np.subtract(a,b)

print(sub1)
print(sub2)

[[-9 -1 -4  3]
 [ 8 16 24 32]]
[[-9 -1 -4  3]
 [ 8 16 24 32]]


In [180]:
mul1 = a*b
mul2 = np.multiply(a,b)

print(mul1)
print(mul2)

[[  0   2  12   0]
 [ 20  80 180 320]]
[[  0   2  12   0]
 [ 20  80 180 320]]


In [181]:
div1 = b/a
div2 = np.divide(b,a)

print(div1)
print(div2)

[[inf 2.  3.  0. ]
 [0.2 0.2 0.2 0.2]]
[[inf 2.  3.  0. ]
 [0.2 0.2 0.2 0.2]]


C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_21964\2470102.py:1: RuntimeWarning: divide by zero encountered in true_divide
  div1 = b/a
C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_21964\2470102.py:2: RuntimeWarning: divide by zero encountered in true_divide
  div2 = np.divide(b,a)


In [182]:
np.exp(a) # e power ...

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17]])

In [183]:
np.sqrt(b)

array([[3.        , 1.41421356, 2.44948974, 0.        ],
       [1.41421356, 2.        , 2.44948974, 2.82842712]])

In [184]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.54402111,  0.91294525, -0.98803162,  0.74511316]])

In [185]:
np.cos(a)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.83907153,  0.40808206,  0.15425145, -0.66693806]])

In [186]:
print(np.log(a)) # element wise natural logarithm

[[      -inf 0.         0.69314718 1.09861229]
 [2.30258509 2.99573227 3.40119738 3.68887945]]


C:\Users\Vishnupriya\AppData\Local\Temp\ipykernel_21964\2740407513.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(a)) # element wise natural logarithm


In [187]:
a = np.full(shape=2,fill_value=5)
b = np.full(2,6)
print(a)
print(b)
a.dot(b) # d0t product

[5 5]
[6 6]


60

In [188]:
a = np.full(shape=(2,2),fill_value=5)
b = np.full((2,2),6)
print(a)
print(b)
a.dot(b) # d0t product

[[5 5]
 [5 5]]
[[6 6]
 [6 6]]


array([[60, 60],
       [60, 60]])

### comparision operations

In [189]:
a = np.array([1,2,3])
b = np.array([1,2,4])
print(a)
print(b)

print(a == b) # element wise comparision
print(a < 2) # element wise comparision
print(np.array_equal(a,b)) # array wise comparison

c = b
print(np.array_equal(b,c))

[1 2 3]
[1 2 4]
[ True  True False]
[ True False False]
False
True


#### aggregate functions

In [190]:
a = np.array([[10,20,30],[21,43,23],[3,8,4]])
print(a)
# a, type(a)cal

[[10 20 30]
 [21 43 23]
 [ 3  8  4]]


In [191]:
a.sum() # array wise sum

162

In [192]:
a.min() # array wise min value

3

In [193]:
a.max() # array wise max value

43

In [194]:
a.cumsum() # cumulative sum of elements

array([ 10,  30,  60,  81, 124, 147, 150, 158, 162])

In [195]:
a.mean() # mean of elements in array
# sum = 10+20+30+21+43+23 = 147
# mean = 147/6 = 24.5

18.0

In [196]:
np.median(a) # median of elements in array
# sorted => 10,20,21,23,30,43
# median => (21+23)/2 = 22

20.0

In [197]:
print(np.corrcoef(a)) # correlation coefficient (row wise)
# https://www.statskingdom.com/correlation-calculator.html

[[1.         0.08219949 0.18898224]
 [0.08219949 1.         0.99419163]
 [0.18898224 0.99419163 1.        ]]


In [198]:
b = np.array([[10,16,30],[3,9,6]])
c = np.array([[13,67,15],[12,98,56]])
# print(b)
# print(c)
print(np.corrcoef(b,c)) 
# correlation coefficient = cov(x,y)/sqrt(var(x) * var(y))
# cov(x,y) = (Sum(Xi - Xmean)(Yi - Ymean) / N-1)

[[ 1.          0.29230641 -0.1930724   0.30511924]
 [ 0.29230641  1.          0.8818947   0.99990987]
 [-0.1930724   0.8818947   1.          0.8754858 ]
 [ 0.30511924  0.99990987  0.8754858   1.        ]]


In [199]:
b.mean(),c.mean()

(12.333333333333334, 43.5)

In [211]:
a = np.array([[1,2],[10,20],[4,5]])
a, np.std(a, axis = 0) # standard deviation = sqrt(mean(x)) 
# https://www.calculator.net/standard-deviation-calculator.html 
# 1,10,4
# 2,20,5

(array([[ 1,  2],
        [10, 20],
        [ 4,  5]]),
 array([3.74165739, 7.87400787]))

**axis = 0 => row wise**

**axis = 1 => column wise**