In [1]:
import numpy as np

In [7]:
a = np.array([[4,2,5,2,6,4,8,3,7,5],[6,2,8,3,5,2,8,9,4,6]])
print(a) 

[[4 2 5 2 6 4 8 3 7 5]
 [6 2 8 3 5 2 8 9 4 6]]


In [8]:
a.sort() # row wise sort
print(a)

[[2 2 3 4 4 5 5 6 7 8]
 [2 2 3 4 5 6 6 8 8 9]]


In [9]:
a = np.array([[4,2,5,2,6,4,8,3,7,5],[6,2,8,3,5,2,8,9,4,6]])
print(a)

[[4 2 5 2 6 4 8 3 7 5]
 [6 2 8 3 5 2 8 9 4 6]]


In [13]:
a.sort(axis = 0) # column wise sort
print(a)

[[4 2 5 2 5 2 8 3 4 5]
 [6 2 8 3 6 4 8 9 7 6]]
