In [1]:
import numpy as np

In [22]:
a = np.array([[4,2,5,2,6,4,8,3,7,5],[6,2,8,3,5,2,8,9,4,10]])
print(a) 

[[ 4  2  5  2  6  4  8  3  7  5]
 [ 6  2  8  3  5  2  8  9  4 10]]


#### indexing

In [23]:
a[0]

array([4, 2, 5, 2, 6, 4, 8, 3, 7, 5])

In [24]:
a[0][2]

5

In [25]:
a[-1]

array([ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10])

In [26]:
a[-1][2]

8

In [27]:
a[-1][-3]

9

#### boolean indexing

In [30]:
# a>5
a[a>5]

array([ 6,  8,  7,  6,  8,  8,  9, 10])

#### fancy indexing

In [40]:
a

array([[ 4,  2,  5,  2,  6,  4,  8,  3,  7,  5],
       [ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10]])

In [41]:
print(a[0][0], a[0][1], a[-1][-1], a[1][4])
print(a[[0,0,-1,1],[0,1,-1,4]]) # (0,0) (0,1) (-1,-1) (1,4)

4 2 10 5
[ 4  2 10  5]


In [46]:
a[[1,0,1,0]][:,[0,1,8,9]]

array([[ 6,  2,  4, 10],
       [ 4,  2,  7,  5],
       [ 6,  2,  4, 10],
       [ 4,  2,  7,  5]])

#### subsetting

In [47]:
a

array([[ 4,  2,  5,  2,  6,  4,  8,  3,  7,  5],
       [ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10]])

In [52]:
print(a[0][9], # indexing
      a[0,9]) # subsetting
print(a[1,:])

5 5
[ 6  2  8  3  5  2  8  9  4 10]


#### slicing

In [72]:
a

array([[40, 20, 50, 20, 60, 40, 80, 30, 70, 50],
       [ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10]])

In [73]:
a[:]

array([[40, 20, 50, 20, 60, 40, 80, 30, 70, 50],
       [ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10]])

In [74]:
a[0:1]

array([[40, 20, 50, 20, 60, 40, 80, 30, 70, 50]])

In [75]:
a[0:2,1]

array([20,  2])

In [78]:
a[:-1,0][0]

40

In [80]:
a[1, ...] # a[1,:]

array([ 6,  2,  8,  3,  5,  2,  8,  9,  4, 10])

In [114]:
a_1d = np.arange(1,25,2)
print(a_1d)
print(a_1d.ndim)

[ 1  3  5  7  9 11 13 15 17 19 21 23]
1


In [123]:
a_1d[-1:-4:-1] # subset

array([23, 21, 19])

In [116]:
a_2d = a.reshape((3,4)) # 3*4 = 12
print(a_2d)
print(a_2d.ndim)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
2


In [122]:
a_2d[1:,:2]  # submatrix

array([[ 9, 11],
       [17, 19]])

In [124]:
a_3d = a.reshape((1,3,4)) # 3*4 = 12
print(a_3d)
print(a_3d.ndim)

[[[ 1  3  5  7]
  [ 9 11 13 15]
  [17 19 21 23]]]
3


In [126]:
a_3d[0,:,:]

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [127]:
a_3d[0, ...]

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

**slicing is shallow copy**

In [129]:
a = np.array([[4,2,5,2,6,4,8,3,7,5],[6,2,8,3,5,2,8,9,4,10]])
b = a[:]
print(id(a)==id(b), id(a[0])==id(b[0]))
print(a)
print(b)

False True
[[ 4  2  5  2  6  4  8  3  7  5]
 [ 6  2  8  3  5  2  8  9  4 10]]
[[ 4  2  5  2  6  4  8  3  7  5]
 [ 6  2  8  3  5  2  8  9  4 10]]


In [130]:
b[0] = [ 40,  20,  50,  20,  60,  40,  80,  30,  70,  50]
print(a)
print(b)

[[40 20 50 20 60 40 80 30 70 50]
 [ 6  2  8  3  5  2  8  9  4 10]]
[[40 20 50 20 60 40 80 30 70 50]
 [ 6  2  8  3  5  2  8  9  4 10]]


In [131]:
b = [1,2,3]
print(a)
print(b)

[[40 20 50 20 60 40 80 30 70 50]
 [ 6  2  8  3  5  2  8  9  4 10]]
[1, 2, 3]
