In [129]:
import numpy as np

In [130]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.shape

(9,)

#### change shape of array

In [131]:
# returns array with given dimensions, no change in data
b = a.reshape(3,3)
print(b, b.shape, a, a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) [1 2 3 4 5 6 7 8 9] (9,)


In [132]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
a.resize((3,3)) # original array shape is changed
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### flatten array

In [133]:
c = b.ravel() # returns flatten array (no effect to original array)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### transposing array

In [134]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
# no effect on original array, returns new array 
# shallow copy
b1 = np.transpose(b) 
b2 = b.T
b1,b2,b

(array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

#### add elements to array

In [136]:
np.append(a,[-9,-3]), a, a.shape
# original array is not changed

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, -9, -3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [137]:
np.insert(a,1,-99), a
# original array is not changed

(array([  1, -99,   2,   3,   4,   5,   6,   7,   8,   9]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

#### remove elements from array

In [138]:
a, np.delete(a,1), a
# original array is not changed

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([1, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

#### combining arrays

##### np.concatenate()

In [161]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0)) # row wise concatenation

[[1 2]
 [3 4]
 [5 6]]


In [162]:
print(np.concatenate((a, b.T), axis=1)) # column wise concatenation

[[1 2 5]
 [3 4 6]]


In [163]:
print(np.concatenate((a, b), axis=None)) # flattened

[1 2 3 4 5 6]


##### np.hstack()

In [178]:
# Stack arrays horizontally (column wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [177]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

##### np.vstack()

In [171]:
# Stack arrays in sequence vertically (row wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [172]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

##### np.r_()

In [173]:
# Stack arrays in sequence vertically (row wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [174]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.r_[a,b]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

##### np.column_stack()

In [187]:
# Stack 1-D arrays as columns into a 2-D array.
a = np.array((1,2,3))
b = np.array((4,5,6))
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

##### np.c_()

In [186]:
# Stack arrays in sequence vertically (row wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

#### splitting arrays

In [216]:
# Split an array into multiple sub-arrays horizontally (column-wise).
a = np.array([ [ 0.,   1.,   2.,   3.],
               [ 4.,   5.,   6.,   7.],
               [ 8.,   9.,  10.,  11.],
               [12.,  13.,  14.,  15.] ])
print(np.hsplit(a,2))

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [220]:
# Split an array into multiple sub-arrays vertically (row-wise).
np.vsplit(a,2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]